import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


type HomePageProps = {

};

const Home: NextPage<HomePageProps> = () => {


	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Link href='poker'>
					<button>Play poker</button>
				</Link>
			</main>
		</div>
	)
}

export default Home