import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef, useState } from 'react'
import { Card } from '../lib/components/Card'
import { HandView } from '../lib/components/HandView'
import { makeDeck } from '../lib/logic/makeDeck'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	const deck = useRef(makeDeck())
	const hands = useRef(deck.current.deal(1))

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				{hands.current.map((hand, i) => (
					<HandView hand={hand} key={i} deck={deck.current} />
				))}
			</main>
		</div>
	)
}

export default Home
