import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Card } from '../lib/components/Card'
import { HandView, makeDeck } from '../lib/components/HandView'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [deck, setDeck] = useState(makeDeck())
  const [hands, setHands] = useState(deck.deal(2))

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <HandView hand={hands[0]} onHitClicked={() => { hands[0].hit(deck); setHands((h) => [...h]) }} />
        <HandView hand={hands[1]} onHitClicked={() => { hands[1].hit(deck); setHands([...hands]) }} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
