import type { GetServerSideProps, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { HandView } from '../lib/components/HandView'
import { deal } from '../lib/logic/deal'
import { draw } from '../lib/logic/draw'
import { shuffle } from '../lib/logic/shuffle'
import { allCards, Cards } from '../lib/types/Card'
import { Deck } from '../lib/types/Deck'
import { Hand } from '../lib/types/Hand'
import styles from '../styles/Poker.module.css'


type PokerPageProps = {
    startingDeck: Deck;
    startingHands: Hand[];
};

const Poker: NextPage<PokerPageProps> = ({
    startingDeck,
    startingHands
}) => {
    const [deck, setDeck] = useState(startingDeck);
    const [hands, setHands] = useState(startingHands)

    return (
        <div className={styles.container}>
            <Head>
                <title>Poker</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                {hands.map((hand, i) => (
                    <HandView hand={hand} key={i} handleOnHit={() => {
                        const { newDeck, newHand } = draw({
                            deck,
                            hand
                        });
                        setHands((h) => {
                            const h2 = [...h];
                            h2[i] = newHand;
                            return h2;
                        });
                        setDeck(newDeck)
                    }} />
                ))}

            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<PokerPageProps> = async () => {

    const shuffledDeck = shuffle(Object.keys(allCards) as Cards)

    const { deck: startingDeck, hands: startingHands } = deal({
        cardsPerHand: 2,
        deck: shuffledDeck,
        numberOfHands: 3,
    })

    return {
        props: {
            startingDeck,
            startingHands,
        }
    }
}

export default Poker